apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: test #Mention the isolated namespace
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80 # Default Nginx port is 80
    # Resource Quota
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2" # CPU limit is 2 cores
