apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-label

  template:
    metadata:
      labels:
        app: nginx-rs-label # Must match selector.matchLabels

    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
