apiVersion: v1
kind: Pod
metadata:
  name: nginx-limitrange
  namespace: test
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "400m" # Within max (2 cores) and ratio (4)
        memory: "256Mi" # Within max (2Gi) and ratio (2)
